/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;

public class App {

    public static void main(String[] args) {
        System.out.println("\u2591\u2592\u2592 Iniciando o servidor \u2592\u2592\u2591");

        int porta = 1234;

        try (ServerSocket servidor = new ServerSocket(1234)) {

            Socket cliente = servidor.accept();
            System.out.println("Cliente conectado: " + cliente.getInetAddress());

            // Estabelecimento dos fluxos de entrada e saída
            BufferedReader entrada = new BufferedReader(new InputStreamReader(cliente.getInputStream(), "UTF-8"));
            DataOutputStream saida = new DataOutputStream(cliente.getOutputStream());

            // Comunicação
            String recebido;

            do {
                recebido = entrada.readLine();
                System.out.println("C > " + recebido);
                saida.writeBytes("S > " + recebido.toUpperCase() + "\n");
            } while(!recebido.equals("sair"));

        }catch (IOException e){
            System.err.println("Erro ao iniciar o servidor: " + e.getMessage());
        }

    }

}
