/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        System.out.println("..:: Inciando cliente ::..");

        String ipServidor = "localhost";
        int portaServidor = 1234;

        try (Socket conexao = new Socket(ipServidor, portaServidor)) {

            System.out.println("Conectado ao servidor...");

            // Estabelecimento dos fluxos de entrada e saída
            BufferedReader entrada = new BufferedReader(new InputStreamReader(conexao.getInputStream(), "UTF-8"));
            DataOutputStream saida = new DataOutputStream(conexao.getOutputStream());

            // Comunicação
            String recebido;
            Scanner teclado = new Scanner(System.in);
            String escritaCliente;

            do{
                System.out.print("> ");
                escritaCliente = teclado.nextLine();
                saida.writeBytes(escritaCliente + "\n");
                saida.flush();

                recebido = entrada.readLine();
                System.out.println(recebido);
            }while(!escritaCliente.equals("sair"));


        }catch(IOException e){
            System.out.println("Erro ao conectar: " + e.getMessage());
        }


    }
}
